### ISSUE TITLE
Hey there 👋

### ISSUE THREAD

**Issue by demberto** [ZappyMan/FL-Studio-Time-Calculator#2]
I just found out this repo and came to say that if you are interested in a *nearly complete* FLP format parser, you should look at [PyFLP](https://github.com/demberto/PyFLP).

Its in Python btw, so it would be real nice if you wish to become a contributor 😊

I didn't mail you directly, although you have a contact method, since most services always mark Protonmail as spam.

**Comment by ZappyMan** [comment]
Hello!
I think I'm gonna stick with my current parsing library (If it aint broke, don't fix it), but if I find motivation in the future to clean up this project I'll look into implementing your system. 
But thank you for taking interest in our project!
